// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemaEscolar.DataAccess;

#nullable disable

namespace sistemaEscolar.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220518060818_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("sistemaEscolar.Models.Alunos", b =>
                {
                    b.Property<int>("idAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dtCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeAluno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("stAtivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("idAluno");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("sistemaEscolar.Models.Materias", b =>
                {
                    b.Property<int>("idMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeMateria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("pesoProva1")
                        .HasColumnType("REAL");

                    b.Property<float>("pesoProva2")
                        .HasColumnType("REAL");

                    b.Property<float>("pesoProva3")
                        .HasColumnType("REAL");

                    b.HasKey("idMateria");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("sistemaEscolar.Models.PeriodosAcademico", b =>
                {
                    b.Property<int>("idPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dtCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("nomePeriodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idPeriodo");

                    b.ToTable("PeriodoAcademico");
                });

            modelBuilder.Entity("sistemaEscolar.Models.Professores", b =>
                {
                    b.Property<int>("idProfessor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dtCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeProfessor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("stAtivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("idProfessor");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("sistemaEscolar.Models.ProvasDetalhe", b =>
                {
                    b.Property<int>("idProvaDetalhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idAluno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idMateria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idPeriodo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idTurma")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ntProva1")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ntProva2")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ntProva3")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ntProva4")
                        .HasColumnType("TEXT");

                    b.Property<bool>("stAprovado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("stRecuperacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("idProvaDetalhe");

                    b.ToTable("ProvaDetalhe");
                });

            modelBuilder.Entity("sistemaEscolar.Models.Tumas", b =>
                {
                    b.Property<int>("idTurma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dtCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("nmTurma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("qtAlunos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("stAtivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("idTurma");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("sistemaEscolar.Models.TurmasDetalhe", b =>
                {
                    b.Property<int>("idTurmaDetalhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idAluno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idMateria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idPeriodo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idProfessor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idTurma")
                        .HasColumnType("INTEGER");

                    b.HasKey("idTurmaDetalhe");

                    b.ToTable("TurmaDetalhe");
                });

            modelBuilder.Entity("sistemaEscolar.Models.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createData")
                        .HasColumnType("TEXT");

                    b.Property<string>("nameUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("passwordUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idUser");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
